<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.16.0" />
    <PackageReference Include="NAudio.Core" Version="2.3.0" />
    <PackageReference Include="NAudio.Midi" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>